### PR TITLE
upgraded to 2.0.0

### PR DESCRIPTION
**Pull request by damiandennis**

### CODE REVIEW

**Comment by sireneweb** [comment]
Good news please don't forget npm :)

**Comment by jbrekle** [comment]
@dougludlow I need dis

**Comment by jbrekle** [comment]
looks like the tests fail randomly

**Comment by RoopeHakulinen** [comment]
I think you should now trust to the Angular 2 following the semantic versioning and use ^ in dependencies. Also there is currently the ^ for `@angular/forms` for some reason.

**Comment by dougludlow** [comment]
@damiandennis, @jbrekle, @RoopeHakulinen - Thanks a ton guys. I pulled in these changes manually and updated the tests to use the Angular2 and everything should be good to go in v0.9.2.

**Pull request closed without merging**
